name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: SSH and Deploy on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest backend image from ECR..."

            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 454781577946.dkr.ecr.us-east-1.amazonaws.com

            docker stop backend || true
            docker rm backend || true

            docker pull 454781577946.dkr.ecr.us-east-1.amazonaws.com/twxt/backend:latest

            docker run -d --name backend -p 5000:5000 454781577946.dkr.ecr.us-east-1.amazonaws.com/twxt/backend:latest
