name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests-and-lint:
    runs-on: ubuntu-latest
    container:
      image: node:20
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      CLIENT_URL: ${{ secrets.CLIENT_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Run lint
        run: npm run lint

  build-and-push:
    needs: tests-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get CLIENT_URL from SSM
        id: get-client-url
        run: |
          CLIENT_URL=$(aws ssm get-parameter --name "/twxt/frontend_url" --with-decryption --query "Parameter.Value" --output text)
          echo "CLIENT_URL=$CLIENT_URL" >> $GITHUB_ENV

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 454781577946.dkr.ecr.us-east-1.amazonaws.com

      - name: Build & Tag Docker image
        run: |
          docker build --build-arg CLIENT_URL=$CLIENT_URL -t backend .
          docker tag backend:latest 454781577946.dkr.ecr.us-east-1.amazonaws.com/twxt/backend:latest

      - name: Push Docker image
        run: docker push 454781577946.dkr.ecr.us-east-1.amazonaws.com/twxt/backend:latest
