name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests-and-lint:
    runs-on: ubuntu-latest
    container:
      image: node:20
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Run lint
        run: npm run lint

  build-and-push:
    needs: tests-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 533267198510.dkr.ecr.us-east-1.amazonaws.com

      - name: Build & Tag Docker image
        run: |
          docker build -t backend ./twxt-server
          docker tag backend:latest 533267198510.dkr.ecr.us-east-1.amazonaws.com/twxt/backend:latest

      - name: Push Docker image
        run: docker push 533267198510.dkr.ecr.us-east-1.amazonaws.com/twxt/backend:latest
